### ISSUE TITLE
Bug: node always have `id` even if `key` is set to something else

### ISSUE THREAD

**Issue by mxstbr** [StellateHQ/fuse#122]
## Description

![CleanShot 2024-01-16 at 12 24 16@2x](https://github.com/StellateHQ/fuse/assets/7525670/626fb0c6-1d1a-4863-92e1-de1c698a43a1)

My `User` type has a `username` key. The underlying data does not have an `id`. Yet, the generated GraphQL object type has `User.id` even though that field doesn't exist.

`User.username` is also nullable in the GraphQL schema even though it is the `key`.

**Comment by JoviDeCroock** [comment]
I mean, the key is used to generate the id property. A node needs a key and you are telling us that we can generate that from username. This is intended behaviour, it's true however that a nullable field should warn in ts
