### ISSUE TITLE
RFC: Allow overriding the `id` field

### ISSUE THREAD

**Issue by mxstbr** [StellateHQ/fuse#128]
## Summary

I have a type called `Story` that has an ID that is always a string. However, Fuse auto-generates `id: ID!`, which (in TypeScript) converts to `string | number`. That, in turn, means that I'm getting errors from typechecking when I do `story.id.replace(…)` because `.replace` doesn't exist on `number`—but my ID will always be a string!

<img width="713" alt="CleanShot 2024-01-18 at 07 14 48@2x" src="https://github.com/StellateHQ/fuse/assets/7525670/3a6e55a2-28b3-4d5e-954f-81170b45b99f">

## Proposed Solution

Allow overriding the `id` field manually:

```ts
export const Story = node({
  // …
  fields: t => ({
    id: t.exposeString('id', { nullable: false })
  })
})
```

**Comment by mxstbr** [comment]
That would work, but override it for all types, right? 

I have other types that do have numeric IDs.

**Comment by JoviDeCroock** [comment]
How is that possible, the base64 identifier is always a string, no?

**Comment by mxstbr** [comment]
Oh right, I forgot that we make IDs globally unique while I was reworking an existing app that does `story.id.replace`—but of course, `story.id` used to be the non-opaque ID.
